### ISSUE TITLE
关于云硬盘和磁盘的叫法疑问

### ISSUE THREAD

**Issue by fighting-go-go-go** [huaweicloudDocs/evs#2]
云硬盘简称磁盘，那什么时候叫哪种有要求么？比如资料中有扩容云硬盘和修改磁盘名称的章节。

**Comment by YoungSamLiu** [comment]
> 云硬盘简称磁盘，那什么时候叫哪种有要求么？比如资料中有扩容云硬盘和修改磁盘名称的章节。

感谢您的宝贵建议。通常使用“云硬盘”一词，当控制台界面为“磁盘”时，为了与界面保持一致，会使用“磁盘”。
