### ISSUE TITLE
错误码说明.md--处理措施修改

### ISSUE THREAD

**Issue by fanqiny** [huaweicloudDocs/evs#6]
EVS.1018只写了参数要求请参见API参考，有点生硬，建议改为：参数要求请参考《云硬盘接口参考》中对应API使用指导的参数说明。

**Comment by YoungSamLiu** [comment]
> EVS.1018只写了参数要求请参见API参考，有点生硬，建议改为：参数要求请参考《云硬盘接口参考》中对应API使用指导的参数说明。

感谢您的宝贵建议，已修改。
